/*
 * File: app/store/TimeStore.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.store.TimeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Lab12_1.model.TimeModel',
        'Ext.data.proxy.LocalStorage'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TimeStore',
            autoLoad: 'getStore',
            autoSync: true,
            model: 'Lab12_1.model.TimeModel',
            proxy: {
                type: 'localstorage',
                id: 'timeStore'
            }
        }, cfg)]);
    },

    getStore: function() {
            var i,obj;
            var store=[];
            for(i=0;i<localStorage.getItem('timeStore-counter');i++) {
                    obj = JSON.parse(localStorage.getItem('timeStore-' + (i + 1)));
                    store.push(obj);

            }
        return store;
    }

});