/*
 * File: app/store/TimeStore.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.store.TimeStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.LocalStorage',
        'Lab12_1.model.TimeModel'
    ],
  constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'TimeStore',
            model: 'Lab12_1.model.TimeModel',
            data: getStore()/*[
                {
                    Start: '9/25/2012',
                    End: '11/12/2003',
                    Time: 481,
                    Comment: 'et'
                },
                {
                    Start: '2/15/2005',
                    End: '12/13/2009',
                    Time: 193,
                    Comment: 'eos'
                },
                {
                    Start: '5/11/2003',
                    End: '9/16/2012',
                    Time: 534,
                    Comment: 'voluptas'
                },
                {
                    Start: '9/24/2002',
                    End: '4/3/2004',
                    Time: 947,
                    Comment: 'sint'
                },
                {
                    Start: '10/22/2008',
                    End: '11/27/2013',
                    Time: 947,
                    Comment: 'quia'
                }
            ]*/,
            proxy: {
                type: 'localstorage',
                id: 'timeStore'
            }
        }, cfg)]);
    }

});
function getStore() {
    var i,obj;
    var store=[];
    for(i=0;i<localStorage.getItem('timeStore-counter');i++) {
            obj = JSON.parse(localStorage.getItem('timeStore-' + (i + 1)));

if(obj!=null) {
  //  var start=Ext.Date.Format(obj.start,'d/m/Y');
    //console.log(start);
}
    }
    return store;
}