/*
 * File: app/view/TimeFormPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.view.TimeFormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.timeformpanel',

    requires: [
        'Lab12_1.view.TimeFormPanelViewModel',
        'Ext.field.Time',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.field.Number',
        'Ext.Button',
        'Ext.Spacer'
    ],

    viewModel: {
        type: 'timeformpanel'
    },
    title: 'Add new time',

    items: [
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'start',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'timefield',
                    margin: 25,
                    maxWidth: 250,
                    label: 'Start Time',
                    placeholder: '12:00'
                },
                {
                    xtype: 'datefield',
                    margin: 25,
                    maxWidth: 250,
                    label: 'Start Date',
                    placeholder: '13/04/2019',
                    picker: {
                        xtype: 'datepicker',
                        title: 'My Panel'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'timefield',
                    margin: 25,
                    maxWidth: 250,
                    label: 'End Time',
                    placeholder: '14:00'
                },
                {
                    xtype: 'datefield',
                    margin: 25,
                    maxWidth: 250,
                    label: 'End Date',
                    placeholder: '13/04/2019',
                    picker: {
                        xtype: 'datepicker',
                        title: 'My Panel'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'numberfield',
                    margin: 25,
                    maxWidth: 250,
                    label: 'Total time',
                    placeholder: '2',
                    minValue: 0
                }
            ]
        },
        {
            xtype: 'container',
            items: [
                {
                    xtype: 'textfield',
                    margin: 25,
                    label: 'Comment',
                    placeholder: 'This is an original comment'
                }
            ]
        },
        {
            xtype: 'container',
            centered: true,
            docked: 'bottom',
            padding: 25,
            layout: {
                type: 'box',
                align: 'start',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    handler: function(button, e) {

                    },
                    ui: 'confirm',
                    maxWidth: 250,
                    minWidth: 150,
                    text: 'Confirm'
                },
                {
                    xtype: 'spacer',
                    width: 25
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('panel').close();
                    },
                    ui: 'decline',
                    maxWidth: 250,
                    minWidth: 150,
                    text: 'Decline'
                }
            ]
        }
    ]

});