/*
 * File: app/view/TimeFormPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.view.TimeFormPanel', {
    extend: 'Ext.form.Panel',
    alias: 'widget.timeformpanel',

    requires: [
        'Lab12_1.view.TimeFormPanelViewModel',
        'Lab12_1.view.TimeFormPanelViewController',
        'Ext.Container',
        'Ext.field.Number',
        'Ext.Button',
        'Ext.Spacer'
    ],

    controller: 'timeformpanel',
    viewModel: {
        type: 'timeformpanel'
    },
    title: 'Add new time',

    items: [
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'start',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    id: 'StartTimeAndDateId',
                    itemId: 'StartTimeAndDate',
                    margin: 25,
                    label: 'Start',
                    placeholder: '14/02/2019 10:00',
                    listeners: {
                        focusleave: 'onStartTimeAndDateFocusleave'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    id: 'EndTimeAndDateId',
                    itemId: 'EndTimeAndDate',
                    margin: 25,
                    label: 'End',
                    placeholder: '14/02/2019 12:00',
                    listeners: {
                        focusleave: 'onEndTimeAndDateFocusleave'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'numberfield',
                    id: 'TotalTimeId',
                    itemId: 'TotalTime',
                    margin: 25,
                    label: 'Total time',
                    placeholder: '2',
                    minValue: 0,
                    listeners: {
                        focusleave: 'onTotalTimeFocusleave'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            id: 'CommentId',
            items: [
                {
                    xtype: 'textfield',
                    itemId: 'Comment',
                    margin: 25,
                    label: 'Comment',
                    placeholder: 'This is an original comment'
                }
            ]
        },
        {
            xtype: 'container',
            centered: true,
            padding: 25,
            layout: {
                type: 'box',
                align: 'start',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'button',
                    itemId: 'Confirm',
                    ui: 'confirm',
                    maxWidth: 250,
                    minWidth: 150,
                    text: 'Confirm',
                    listeners: {
                        tap: 'addToStore'
                    }
                },
                {
                    xtype: 'spacer',
                    width: 25
                },
                {
                    xtype: 'button',
                    handler: function(button, e) {
                        this.up('panel').close();
                    },
                    ui: 'decline',
                    maxWidth: 250,
                    minWidth: 150,
                    text: 'Decline'
                }
            ]
        }
    ],
    listeners: {
        added: 'onFormpanelAdded'
    }

});