/*
 * File: app/view/TimeFormPanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.view.TimeFormPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.timeformpanel',

    onStartTimeAndDateFocusleave: function(component, event, eOpts) {
        var startTime = Ext.getCmp("StartTimeAndDateId").getValue();
        var endTime = Ext.getCmp("EndTimeAndDateId").getValue();
        var totalTime = Ext.getCmp("TotalTimeId").getValue();

        var startDate = new Date(startTime);

        console.log(startDate);
    },

    onEndTimeAndDateFocusleave: function(component, event, eOpts) {
        var startTime = Ext.getCmp("StartTimeAndDateId").getValue();
        var endTime = Ext.getCmp("EndTimeAndDateId").getValue();
        var totalTime = Ext.getCmp("TotalTimeId").getValue();
        console.log(startTime + endTime + totalTime);
    },

    onTotalTimeFocusleave: function(component, event, eOpts) {
        var startTime = Ext.getCmp("StartTimeAndDateId").getValue();
        var endTime = Ext.getCmp("EndTimeAndDateId").getValue();
        var totalTime = Ext.getCmp("TotalTimeId").getValue();
        console.log(startTime + endTime + totalTime);
    },

    onFormpanelAdded: function(component, container, index, eOpts) {
        var currDate = new Date();

        Ext.getCmp("StartTimeAndDateId").setValue(currDate);
        Ext.getCmp("EndTimeAndDateId").setValue(currDate);
        Ext.getCmp("TotalTimeId").setValue(0);
    }

});