/*
 * File: app/view/TimeTabPanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.view.TimeTabPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.timetabpanel',

    OnItemSelected: function(dataview, selected, eOpts) {

    },

    onContainerInitialize: function(component, eOpts) {

        var currDate = new Date();



        var dd = currDate.getDate();
        var mm = currDate.getMonth() + 1; //January is 0!

        var yyyy = currDate.getFullYear();

        if (dd < 10)
        {
            dd = '0' + dd;
        }

        if (mm < 10)
        {
            mm = '0' + mm;
        }

        var HH = currDate.getHours();
        var MM = currDate.getMinutes();

        if(HH < 10)
        {
            HH = "0" + HH;
        }
        if(MM < 10)
        {
            MM = "0" + MM;
        }

        currDate = dd + '/' + mm + '/' + yyyy;


        Ext.getCmp('DayId').setTitle(currDate);


        // TODO: Load this week
        //this.up('tabpanel').down('tab[text=Example]').el.applyStyles('background:red');

    },

    onTabpanelActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
        /*var currDate = new Date();



        var dd = currDate.getDate();
        var mm = currDate.getMonth() + 1; //January is 0!

        var yyyy = currDate.getFullYear();

        if (dd < 10)
        {
        dd = '0' + dd;
        }

        if (mm < 10)
        {
        mm = '0' + mm;
        }

        var HH = currDate.getHours();
        var MM = currDate.getMinutes();

        if(HH < 10)
        {
        HH = "0" + HH;
        }
        if(MM < 10)
        {
        MM = "0" + MM;
        }

        currDate = dd + '/' + mm + '/' + yyyy;



        Ext.getCmp('DayId').setTitle(currDate);
        this.down("tabpanel").getCmp("DayId").setTitle("reee");


        // TODO: Load this week
        //this.up('tabpanel').down('tab[text=Example]').el.applyStyles('background:red');*/
    }

});