/*
 * File: app/view/TimeTabPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.view.TimeTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.timetabpanel',

    requires: [
        'Lab12_1.view.TimeTabPanelViewModel',
        'Ext.Button',
        'Ext.TitleBar',
        'Ext.grid.Grid',
        'Ext.grid.column.Date',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'timetabpanel'
    },
    fullscreen: false,

    layout: {
        type: 'card',
        animation: false
    },
    items: [
        {
            xtype: 'container',
            title: 'Day',
            layout: {
                type: 'vbox',
                align: 'center'
            },
            items: [
                {
                    xtype: 'container',
                    margin: 15,
                    maxWidth: 150,
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, e) {
                                Ext.create('Lab12_1.view.TimeFormPanel', {fullscreen: true});
                            },
                            itemId: 'mybutton',
                            ui: 'confirm',
                            docked: 'top',
                            text: 'Add time'
                        }
                    ]
                },
                {
                    xtype: 'titlebar',
                    docked: 'top',
                    title: '03/05/2019',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            ui: 'square',
                            margin: '0, 0, 0, 400',
                            text: '<'
                        },
                        {
                            xtype: 'button',
                            align: 'right',
                            ui: 'square',
                            margin: '0, 400, 0, 0',
                            text: '>'
                        }
                    ]
                },
                {
                    xtype: 'grid',
                    height: '100%',
                    width: '100%',
                    store: 'TimeStore',
                    columns: [
                        {
                            xtype: 'datecolumn',
                            width: 129,
                            dataIndex: 'Start',
                            text: 'Start',
                            format: 'd-M-Y H:i'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 124,
                            dataIndex: 'End',
                            text: 'End',
                            format: 'd-M-Y H:i'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 96,
                            dataIndex: 'Time',
                            text: 'Time'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 266,
                            dataIndex: 'Comment',
                            text: 'Comment'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            title: 'Week',
            items: [
                {
                    xtype: 'titlebar',
                    docked: 'top',
                    title: '29/04/2019 - 05/05/2019',
                    layout: {
                        type: 'hbox',
                        align: 'center',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'button',
                            ui: 'square',
                            margin: '0, 0, 0, 400',
                            text: '<'
                        },
                        {
                            xtype: 'button',
                            align: 'right',
                            ui: 'square',
                            margin: '0, 400, 0, 0',
                            text: '>'
                        }
                    ]
                },
                {
                    xtype: 'grid',
                    height: '100%',
                    width: '100%',
                    store: 'TimeStore',
                    columns: [
                        {
                            xtype: 'datecolumn',
                            width: 129,
                            dataIndex: 'date',
                            text: 'Start'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 124,
                            text: 'End'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 96,
                            text: 'Time'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 266,
                            text: 'Comment'
                        }
                    ]
                }
            ]
        }
    ]

});