/*
 * File: app/view/TimeFormPanelViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.view.TimeFormPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.timeformpanel',

    onFormpanelAdded: function(component, container, index, eOpts) {
        var today = new Date();

        var dd = today.getDate();
        var mm = today.getMonth() + 1; //January is 0!

        var yyyy = today.getFullYear();
        if (dd < 10) {
            dd = '0' + dd;
        }
        if (mm < 10) {
            mm = '0' + mm;
        }

        var HH = today.getHours();
        var MM = today.getMinutes();

        if(HH < 10)
        {
            HH = "0" + HH;
        }
        if(MM < 10)
        {
            MM = "0" + MM;
        }

        var today = dd + '/' + mm + '/' + yyyy + " " + HH + ":" + MM;

        Ext.getCmp("StartTimeAndDateId").setValue(today);
        Ext.getCmp("EndTimeAndDateId").setValue(today);
        Ext.getCmp("TotalTimeId").setValue("0.0");
    }

});