/*
 * File: app/view/UpdateTimeFormPanelViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.5.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.7.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.7.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Lab12_1.view.UpdateTimeFormPanelViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.updatetimeformpanel',

    addToStore: function() {

                var store= Ext.getStore("timeStore");
                var startTime = Ext.getCmp("StartTimeAndDateId").getValue();
                        var endTime = Ext.getCmp("EndTimeAndDateId").getValue();
                        var totalTime = Ext.getCmp("TotalTimeId").getValue();
                        var comment= Ext.getCmp("Comment").getValue();
                var timeFormat={
                                    Start: startTime,
                                    End: endTime,
                                    Time: totalTime,
                                    Comment: comment
                                };
                store.add(timeFormat);
                store.sync();


    },

    updateStore: function() {
                var store= Ext.getStore("timeStore");
                var startTime = Ext.getCmp("StartTimeAndDateId").getValue();
                var endTime = Ext.getCmp("EndTimeAndDateId").getValue();
                var totalTime = Ext.getCmp("TotalTimeId").getValue();
                var comment= Ext.getCmp("Comment").getValue();
                var timeFormat={
                                    Start: startTime,
                                    End: endTime,
                                    Time: totalTime,
                                    Comment: comment
                                };
                store.update(timeFormat);
                store.sync();
    }

});